import type { CardDefinition, CardId, CardKind } from '../domain/types'

export const KIND_NAMES: Record<CardKind, string> = {
  因: '创造条件',
  证: '揭露信息',
  改: '改写时序',
  锚: '固定历史',
  悖: '高风险收益',
}

export const CARDS: Record<CardId, CardDefinition> = {
  seal: {
    id: 'seal',
    name: '封锁仓库',
    kind: '因',
    cost: 1,
    text: '在固定事件前生效：抵挡该事件造成的时间线损伤。',
    flavor: '不阻止悖论、失去真相或可信度变化。',
  },
  rescue: {
    id: 'rescue',
    name: '紧急疏散',
    kind: '因',
    cost: 1,
    text: '置于「现在」：真相 +1，并保护证人。',
    flavor: '正确的行动需要正确的时刻。',
  },
  ledger: {
    id: 'ledger',
    name: '账本残页',
    kind: '证',
    cost: 1,
    text: '真相 +2；若证人存活，改为 +3。',
    flavor: '灰烬没有烧掉所有数字。',
  },
  clarify: {
    id: 'clarify',
    name: '澄清谣言',
    kind: '证',
    cost: 1,
    text: '可信度 +1；在事件前可破解谣言。',
    flavor: '事实需要赶在声音前面。',
  },
  memory: {
    id: 'memory',
    name: '真实记忆',
    kind: '改',
    cost: 2,
    text: '真相 +3，悖论 +2；置于过去时真相 +4。',
    flavor: '记忆可以重写证据。',
  },
  anchor: {
    id: 'anchor',
    name: '时间锚',
    kind: '锚',
    cost: 1,
    text: '在事件前锚定真相，悖论 -1。',
    flavor: '把一页纸钉在世界上。',
  },
  alibi: {
    id: 'alibi',
    name: '伪造口供',
    kind: '悖',
    cost: 1,
    text: '可信度 +2，真相 +1，悖论 +2。',
    flavor: '好用的谎言通常只好用一次。',
  },
  blackout: {
    id: 'blackout',
    name: '提前停电',
    kind: '改',
    cost: 1,
    text: '置于过去：取消固定事件，悖论 +2。',
    flavor: '让事故发生在事故之前。',
  },
  annotation: {
    id: 'annotation',
    name: '逆序批注',
    kind: '改',
    cost: 1,
    text: '真相 +1；置于未来时改为 +3。',
    flavor: '这行字来自尚未写下它的人。',
  },
  echo: {
    id: 'echo',
    name: '因果回响',
    kind: '证',
    cost: 1,
    text: '每有一种已打出的不同标签，真相 +1。',
    flavor: '不同的原因指向同一个结果。',
  },
  testimony: {
    id: 'testimony',
    name: '封存口供',
    kind: '锚',
    cost: 1,
    text: '可信度 +1；若已有可信度，真相 +2。',
    flavor: '说出口的话也能成为锚。',
  },
  vow: {
    id: 'vow',
    name: '以身作证',
    kind: '悖',
    cost: 2,
    text: '真相 +5；若悖论≥4，再 +2，但时间线 -2。',
    flavor: '有些证据只能用自己签名。',
  },
  thread: {
    id: 'thread',
    name: '红线追迹',
    kind: '证',
    cost: 0,
    text: '真相 +1；若置于现在，可信度 +1。',
    flavor: '所有名字都被一根线牵住。',
  },
  delay: {
    id: 'delay',
    name: '延迟发生',
    kind: '因',
    cost: 1,
    text: '抵挡本轮灾害；若置于未来，真相 +1。',
    flavor: '不是阻止，只是让它晚一点。',
  },
  doorplate: {
    id: 'doorplate',
    name: '燃烧的门牌',
    kind: '因',
    cost: 1,
    text: '抵挡本轮灾害；置于过去时真相 +2。',
    flavor: '门牌先燃烧，房间才决定起火。',
  },
  chorus: {
    id: 'chorus',
    name: '双重证词',
    kind: '证',
    cost: 2,
    text: '真相 +3；若可信度≥1，再 +2。',
    flavor: '两个人说出同一个未来。',
  },
  rewind: {
    id: 'rewind',
    name: '回到案发前',
    kind: '改',
    cost: 2,
    text: '置于过去：取消事件；时间线回复 2，悖论 +2。',
    flavor: '你不是第一次推开这扇门。',
  },
  sealorder: {
    id: 'sealorder',
    name: '封存命令',
    kind: '锚',
    cost: 1,
    text: '锚定真相；若本轮已有「证」，再真相 +2。',
    flavor: '命令写下后，连时间也必须签收。',
  },
  erase: {
    id: 'erase',
    name: '删除目击者',
    kind: '悖',
    cost: 1,
    text: '真相 +4，证人死亡，悖论 +2。',
    flavor: '没有证人，也就没有矛盾。',
  },
  secondhand: {
    id: 'secondhand',
    name: '借来的秒针',
    kind: '改',
    cost: 0,
    text: '置于未来：真相 +2；否则悖论 +1。',
    flavor: '它每分钟会多走一秒。',
  },
}

export const START_DECK: CardId[] = [
  'seal',
  'seal',
  'ledger',
  'ledger',
  'rescue',
  'clarify',
  'memory',
  'anchor',
  'alibi',
]

export const REWARD_POOL: CardId[] = [
  'blackout',
  'annotation',
  'echo',
  'testimony',
  'vow',
  'thread',
  'delay',
  'doorplate',
  'chorus',
  'rewind',
  'sealorder',
  'erase',
  'secondhand',
  'anchor',
  'ledger',
  'clarify',
]

