import type { ClueId, EventDefinition, EventId } from '../domain/types'

export const CLUES: Record<ClueId, { name: string; text: string }> = {
  'archive-origin': { name: '档案馆才是起点', text: '仓库火灾只是删除命令留下的烟幕。' },
  'zero-self': { name: '第零号时间线中的自己', text: '另一条历史里的你早已参与这场灾难。' },
  'future-city': { name: '被救下的未来', text: '有人记得一座没有在零点燃烧的白塔城。' },
  'key-shape': { name: '第零号钥匙齿痕', text: '地下那扇门确实为你留下了入口。' },
}

export const EVENTS: Record<EventId, EventDefinition> = {
  telegram: {
    id: 'telegram',
    title: '无字电报',
    narrative: '电报纸上没有一个字。你把它靠近灯火，未来的墨迹才慢慢浮现：仓库不是灾难的起点，档案馆才是。',
    choices: [
      {
        id: 'read',
        icon: '读',
        title: '让未来的文字完全显现',
        description: '将「逆序批注」加入牌组，但接触未来会产生悖论。',
        result: '+1 悖论',
        story: '无字电报证明：档案馆才是灾难起点。',
        effect: { addCards: ['annotation'], paradox: 1, addClues: ['archive-origin'] },
      },
      {
        id: 'burn',
        icon: '焚',
        title: '在读完之前烧掉电报',
        description: '你没有得到答案，但时间线暂时稳定。',
        result: '回复 6',
        story: '你烧掉未来的电报，只记住了纸灰的形状。',
        effect: { timeline: 6 },
      },
    ],
  },
  photo: {
    id: 'photo',
    title: '失真的合影',
    narrative: '照片里站着四个人。证人、监察官、档案管理员，以及一个本不该在场的你。照片背面写着：“剪掉一个人，时间就会忘记他。”',
    choices: [
      {
        id: 'keep',
        icon: '留',
        title: '保留照片中的自己',
        description: '承认另一条时间线的存在，并取得一枚时间锚。',
        result: '最大时间线 -3',
        story: '合影里多出的自己，来自第零号时间线。',
        effect: { maxTimeline: -3, addCards: ['anchor'], addClues: ['zero-self'] },
      },
      {
        id: 'cut',
        icon: '剪',
        title: '把自己从照片里剪掉',
        description: '忘掉一段危险记忆，让悖论下降。',
        result: '悖论 -3',
        story: '照片忘记了你，但镜子没有。',
        effect: { paradox: -3 },
      },
    ],
  },
  platform: {
    id: 'platform',
    title: '不存在的站台',
    narrative: '末班车停在没有编号的站台。车窗里的乘客全都拿着明天的报纸，唯独你的座位上摆着一块正在倒走的秒针。',
    choices: [
      {
        id: 'board',
        icon: '乘',
        title: '坐一站明天的列车',
        description: '带回「借来的秒针」，但列车会从当前时间线上碾过。',
        result: '时间线 -4',
        story: '你从明天的列车上带回一根不属于今天的秒针。',
        effect: { timeline: -4, addCards: ['secondhand'] },
      },
      {
        id: 'wait',
        icon: '候',
        title: '替迷路的乘客保管行李',
        description: '行李里装着前几次循环留下的回声。',
        result: '+8 回声，+1 悖论',
        story: '列车没有等到乘客，只把一箱回声留给了你。',
        effect: { echoes: 8, paradox: 1 },
      },
    ],
  },
  obituary: {
    id: 'obituary',
    title: '提前刊登的讣告',
    narrative: '报纸已经排好明天的讣告。死者一栏写着你的名字，校对员问你是否要修改死亡时间。',
    choices: [
      {
        id: 'sign',
        icon: '签',
        title: '在讣告上签字作证',
        description: '获得「封存口供」，但名字会永久留在时间线外侧。',
        result: '最大时间线 -2',
        story: '你为自己的死讯作证，报纸因此成了一份无法否认的证据。',
        effect: { maxTimeline: -2, addCards: ['testimony'] },
      },
      {
        id: 'redact',
        icon: '涂',
        title: '用黑墨涂掉死亡时间',
        description: '墨迹暂时缝合了伤口，却让事实更加矛盾。',
        result: '回复 5，+1 悖论',
        story: '你涂掉了死亡时间，报纸只好承认你仍然活着。',
        effect: { timeline: 5, paradox: 1 },
      },
    ],
  },
  'unborn-letter': {
    id: 'unborn-letter',
    title: '未出生者的来信',
    narrative: '信封上的寄件人是一个尚未出生的孩子。她说自己记得你阻止火灾后的城市，并请求你不要放弃这条可能。',
    choices: [
      {
        id: 'answer',
        icon: '回',
        title: '沿着红线回信',
        description: '获得「红线追迹」；与不存在的人通信会产生轻微悖论。',
        result: '+1 悖论',
        story: '你把回信系上红线，线的另一端传来尚未出生的心跳。',
        effect: { addCards: ['thread'], paradox: 1, addClues: ['future-city'] },
      },
      {
        id: 'seal',
        icon: '封',
        title: '不拆开第二页',
        description: '让未来保留秘密，当前时间线因此更加稳定。',
        result: '悖论 -2',
        story: '你没有读完来信。被保留的未来因此没有继续泄漏。',
        effect: { paradox: -2 },
      },
    ],
  },
  'zero-key': {
    id: 'zero-key',
    title: '第零号钥匙',
    narrative: '一把钥匙被锁在透明柜里，标签却写着：“此物已于明日归还。”钥匙齿与档案馆地下那扇门完全一致。',
    choices: [
      {
        id: 'take',
        icon: '取',
        title: '提前取走钥匙',
        description: '把钥匙带入当前时间线，并承担篡改保管记录的代价。',
        result: '获得遗物，+2 悖论',
        story: '你取走钥匙，柜中的标签立刻改成了你的笔迹。',
        effect: { addRelic: 'key', paradox: 2, addClues: ['key-shape'] },
      },
      {
        id: 'copy',
        icon: '拓',
        title: '只拓印钥匙齿',
        description: '获得「逆序批注」，不直接触碰那条未来。',
        result: '加入牌组',
        story: '拓印纸记住了钥匙的形状，也记住了它尚未打开的门。',
        effect: { addCards: ['annotation'], addClues: ['key-shape'] },
      },
    ],
  },
}
