import type {
  ChallengeDefinition,
  ChallengeId,
  EncounterDefinition,
  EncounterId,
  IncidentDefinition,
  IncidentId,
  MapNode,
  RelicDefinition,
  RelicId,
} from '../domain/types'

export const CHALLENGES: Record<ChallengeId, ChallengeDefinition> = {
  standard: {
    id: 'standard',
    name: '标准调查',
    timeline: 30,
    paradoxLimit: 8,
    targetMultiplier: 1,
    inkMultiplier: 1,
    text: '推荐首次游玩；规则完整，容错适中。',
  },
  paradox: {
    id: 'paradox',
    name: '悖论挑战',
    timeline: 26,
    paradoxLimit: 7,
    targetMultiplier: 1.15,
    inkMultiplier: 1.5,
    text: '案件真相要求 +15%，时间线与悖论上限降低。',
  },
  zero: {
    id: 'zero',
    name: '零时挑战',
    timeline: 22,
    paradoxLimit: 6,
    targetMultiplier: 1.3,
    inkMultiplier: 2,
    text: '案件真相要求 +30%，以一张伪造口供污染起始牌组。',
  },
}

export const RELICS: Record<RelicId, RelicDefinition> = {
  watch: { id: 'watch', name: '烧焦的怀表', text: '每场案件第一张牌费用为 0。' },
  crane: { id: 'crane', name: '折纸心灯', text: '进入每场案件时修复 2 点时间线。' },
  redthread: { id: 'redthread', name: '朱砂红线', text: '每回合第一张「证」额外获得 1 点真相。' },
  ash: { id: 'ash', name: '灰烬印章', text: '每次取消固定事件时修复 2 点时间线。' },
  mirror: { id: 'mirror', name: '镜面残片', text: '每回合首次增加悖论时获得 1 点真相。' },
  ticket: { id: 'ticket', name: '昨日车票', text: '进入每场案件时获得 1 点可信度。' },
  needle: { id: 'needle', name: '校准银针', text: '每回合第一张「改」费用为 0。' },
  carbon: { id: 'carbon', name: '复写黑纸', text: '每回合第一张已升级牌额外获得 1 点真相。' },
  bellshard: { id: 'bellshard', name: '逆钟碎片', text: '一轮在过去、现在、未来均安排行动时，真相 +2。' },
  lens: { id: 'lens', name: '裂纹目镜', text: '固定事件造成的时间线损伤减少 2 点。' },
  key: { id: 'key', name: '第零号钥匙', text: '进入每场案件时悖论 -1。' },
}

export const INCIDENTS: Record<IncidentId, IncidentDefinition> = {
  fire: { id: 'fire', name: '固定事件：仓库火灾', era: 2, glyph: '火', intent: '未受保护：时间线 -4，证人死亡' },
  interrogation: { id: 'interrogation', name: '固定事件：监察官审讯', era: 1, glyph: '审', intent: '可信度不足：时间线 -3' },
  rumor: { id: 'rumor', name: '固定事件：伪造的报纸', era: 0, glyph: '伪', intent: '未被澄清：可信度归零，悖论 +1' },
  mirror: { id: 'mirror', name: '固定事件：镜像复述', era: 1, glyph: '镜', intent: '标签少于 2 种：时间线 -3' },
  theft: { id: 'theft', name: '固定事件：证物窃取', era: 1, glyph: '窃', intent: '未受保护：时间线 -3' },
  purge: { id: 'purge', name: '固定事件：档案销毁', era: 2, glyph: '毁', intent: '真相未锚定：失去 3 点真相' },
  rewrite: { id: 'rewrite', name: '固定事件：规则改写', era: 1, glyph: '改', intent: '未取消：悖论 +1，时间线 -2' },
  collapse: { id: 'collapse', name: '固定事件：零时坍塌', era: 2, glyph: '零', intent: '真相未锚定：时间线 -6，悖论 +1' },
  toll: { id: 'toll', name: '固定事件：第十三声钟响', era: 2, glyph: '钟', intent: '真相未锚定：时间线 -4' },
  silence: { id: 'silence', name: '固定事件：全城失语', era: 1, glyph: '默', intent: '本轮未打出「证」：时间线 -4' },
  inversion: { id: 'inversion', name: '固定事件：因果倒置', era: 0, glyph: '倒', intent: '本轮未打出「改」：悖论 +2' },
}

export const ENCOUNTERS: Record<EncounterId, EncounterDefinition> = {
  fire: {
    id: 'fire',
    name: '余烬证人',
    type: '普通案件',
    rank: 'normal',
    target: 7,
    incidents: ['fire', 'interrogation', 'fire'],
    story: '她已经在仓库里死过十七次。这一次，她在火起之前看见了你。',
  },
  mirror: {
    id: 'mirror',
    name: '镜廊审讯',
    type: '普通案件',
    rank: 'normal',
    target: 9,
    incidents: ['rumor', 'mirror', 'interrogation'],
    story: '监察官逐字复述你的供词，连停顿都一模一样——比你早半秒。',
  },
  bell: {
    id: 'bell',
    name: '逆行钟楼',
    type: '普通案件',
    rank: 'normal',
    target: 11,
    incidents: ['theft', 'toll', 'inversion', 'fire'],
    story: '钟楼每响一次，城市就倒退一分钟。守钟人已经比自己的出生更年轻。',
  },
  twins: {
    id: 'twins',
    name: '双生书吏',
    type: '精英案件',
    rank: 'elite',
    target: 13,
    incidents: ['theft', 'mirror', 'purge', 'theft'],
    story: '两个书吏共用一段过去。你删除其中一人，另一人便记起两次死亡。',
  },
  faceless: {
    id: 'faceless',
    name: '无面见证人',
    type: '精英案件',
    rank: 'elite',
    target: 15,
    incidents: ['rumor', 'silence', 'inversion', 'purge', 'collapse'],
    story: '所有证人都指向同一个凶手，却没有任何人记得那张脸。',
  },
  curator: {
    id: 'curator',
    name: '封馆人',
    type: '第一幕 Boss · 被删去的值班员',
    rank: 'boss',
    target: 18,
    incidents: ['rumor', 'mirror', 'purge', 'rewrite'],
    story: '封馆人守着一份不存在的值班表。每当你读出一个名字，他就从历史里删去一张脸。',
  },
  station: {
    id: 'station',
    name: '末班车站',
    type: '普通案件',
    rank: 'normal',
    target: 13,
    incidents: ['toll', 'theft', 'inversion', 'collapse'],
    story: '列车每晚驶向明天，却总在昨天清晨送回同一批乘客。',
  },
  hospital: {
    id: 'hospital',
    name: '无明病房',
    type: '普通案件',
    rank: 'normal',
    target: 14,
    incidents: ['silence', 'interrogation', 'fire', 'purge'],
    story: '病历记载着尚未发生的伤口，护士则拒绝承认病床上躺着任何人。',
  },
  press: {
    id: 'press',
    name: '明日报社',
    type: '普通案件',
    rank: 'normal',
    target: 15,
    incidents: ['rumor', 'rewrite', 'inversion', 'rumor'],
    story: '这里每天只印明天的报纸。主编知道所有结果，却从不允许记者报道原因。',
  },
  'chorus-elite': {
    id: 'chorus-elite',
    name: '百口同声',
    type: '精英案件',
    rank: 'elite',
    target: 18,
    incidents: ['silence', 'mirror', 'interrogation', 'purge'],
    story: '一百名证人同时开口，供词完全相同——包括每一次咳嗽和迟疑。',
  },
  undertaker: {
    id: 'undertaker',
    name: '倒签入殓师',
    type: '精英案件',
    rank: 'elite',
    target: 19,
    incidents: ['theft', 'fire', 'collapse', 'purge'],
    story: '入殓师先埋葬死者，再等他们按照墓碑日期死去。你的墓穴已经空了十八次。',
  },
  clockmaker: {
    id: 'clockmaker',
    name: '失刻钟匠',
    type: '第二幕 Boss · 倒走的制造者',
    rank: 'boss',
    target: 24,
    incidents: ['rewrite', 'toll', 'inversion', 'collapse', 'collapse'],
    story: '钟匠承认自己制造了循环，却说订单上的签名属于三天后的你。',
  },
  vault: {
    id: 'vault',
    name: '空白库房',
    type: '普通案件',
    rank: 'normal',
    target: 18,
    incidents: ['purge', 'theft', 'rewrite', 'collapse'],
    story: '库房里没有一份档案，门外的借阅记录却列着全城每个人的名字。',
  },
  tomorrow: {
    id: 'tomorrow',
    name: '明日来客',
    type: '普通案件',
    rank: 'normal',
    target: 19,
    incidents: ['interrogation', 'inversion', 'mirror', 'silence'],
    story: '来客戴着你的脸，声称自己不是未来，而是被你放弃的另一种现在。',
  },
  city: {
    id: 'city',
    name: '燃烧的白塔城',
    type: '普通案件',
    rank: 'normal',
    target: 20,
    incidents: ['fire', 'rumor', 'toll', 'collapse'],
    story: '整座城市同时成为证人和案发现场。每一扇窗都映出不同的火灾起点。',
  },
  double: {
    id: 'double',
    name: '第二个调查员',
    type: '精英案件',
    rank: 'elite',
    target: 23,
    incidents: ['mirror', 'inversion', 'rewrite', 'purge', 'collapse'],
    story: '另一个你带着更完整的笔记。他说唯一的破案方式，是让其中一个调查员从未存在。',
  },
  null: {
    id: 'null',
    name: '零号见证人',
    type: '精英案件',
    rank: 'elite',
    target: 24,
    incidents: ['silence', 'purge', 'collapse', 'inversion', 'collapse'],
    story: '证人没有姓名、出生和影子，但所有档案都引用了他的第一份口供。',
  },
  boss: {
    id: 'boss',
    name: '零时档案',
    type: '固定历史 · Boss',
    rank: 'boss',
    target: 30,
    incidents: ['rewrite', 'fire', 'purge', 'collapse', 'collapse'],
    story: '档案管理员摘下面具。那张脸属于三天后的你。',
  },
}

export const MAP_TEMPLATES: Record<string, MapNode> = {
  fire: { type: 'battle', id: 'fire', icon: '火', title: '余烬证人', sub: '普通案件', description: '救下仓库里的唯一证人' },
  mirror: { type: 'battle', id: 'mirror', icon: '镜', title: '镜廊审讯', sub: '普通案件', description: '监察官知道你下一句供词' },
  bell: { type: 'battle', id: 'bell', icon: '钟', title: '逆行钟楼', sub: '普通案件', description: '每一声钟响都让城市倒退' },
  twins: { type: 'elite', id: 'twins', icon: '双', title: '双生书吏', sub: '精英案件', description: '共享过去的两名守档人' },
  faceless: { type: 'elite', id: 'faceless', icon: '默', title: '无面见证人', sub: '精英案件', description: '全城都忘记了凶手的脸' },
  curator: { type: 'boss', id: 'curator', icon: '封', title: '封馆人', sub: '第一幕固定历史', description: '从值班表里删去所有名字' },
  station: { type: 'battle', id: 'station', icon: '站', title: '末班车站', sub: '普通案件', description: '乘客从明天返回昨天' },
  hospital: { type: 'battle', id: 'hospital', icon: '病', title: '无明病房', sub: '普通案件', description: '病历先于伤口出现' },
  press: { type: 'battle', id: 'press', icon: '报', title: '明日报社', sub: '普通案件', description: '只报道结果的报纸' },
  'chorus-elite': { type: 'elite', id: 'chorus-elite', icon: '众', title: '百口同声', sub: '精英案件', description: '一百份完全相同的供词' },
  undertaker: { type: 'elite', id: 'undertaker', icon: '葬', title: '倒签入殓师', sub: '精英案件', description: '先下葬，再等待死亡' },
  clockmaker: { type: 'boss', id: 'clockmaker', icon: '刻', title: '失刻钟匠', sub: '第二幕固定历史', description: '循环制造者与明日订单' },
  vault: { type: 'battle', id: 'vault', icon: '库', title: '空白库房', sub: '普通案件', description: '没有档案的借阅记录' },
  tomorrow: { type: 'battle', id: 'tomorrow', icon: '明', title: '明日来客', sub: '普通案件', description: '另一种现在里的你' },
  city: { type: 'battle', id: 'city', icon: '城', title: '燃烧的白塔城', sub: '普通案件', description: '全城都是案发现场' },
  double: { type: 'elite', id: 'double', icon: '复', title: '第二个调查员', sub: '精英案件', description: '只能留下一个调查者' },
  null: { type: 'elite', id: 'null', icon: '无', title: '零号见证人', sub: '精英案件', description: '不存在的第一份口供' },
  boss: { type: 'boss', id: 'boss', icon: '零', title: '零时档案', sub: '固定历史', description: '灾难真正的起点' },
  telegram: { type: 'event', id: 'telegram', icon: '函', title: '无字电报', sub: '异常事件', description: '一封来自明天的电报' },
  photo: { type: 'event', id: 'photo', icon: '像', title: '失真的合影', sub: '异常事件', description: '照片上多出一个你' },
  platform: { type: 'event', id: 'platform', icon: '轨', title: '不存在的站台', sub: '异常事件', description: '末班车驶向明天' },
  obituary: { type: 'event', id: 'obituary', icon: '讣', title: '提前刊登的讣告', sub: '异常事件', description: '修改自己的死亡时间' },
  'unborn-letter': { type: 'event', id: 'unborn-letter', icon: '信', title: '未出生者的来信', sub: '异常事件', description: '来自被拯救未来的回信' },
  'zero-key': { type: 'event', id: 'zero-key', icon: '钥', title: '第零号钥匙', sub: '异常事件', description: '此物已于明日归还' },
  rest: { type: 'rest', id: 'rest', icon: '息', title: '回声室', sub: '安全节点', description: '修补时间线或精简牌组' },
  rest2: { type: 'rest', id: 'rest2', icon: '息', title: '午夜墨池', sub: '安全节点', description: '修补、校准或精简牌组' },
  shop: { type: 'shop', id: 'shop', icon: '铺', title: '倒悬书摊', sub: '交易节点', description: '用回声交换牌与遗物' },
  rest3: { type: 'rest', id: 'rest3', icon: '息', title: '候车钟室', sub: '安全节点', description: '校准、缝合或精简牌组' },
  rest4: { type: 'rest', id: 'rest4', icon: '息', title: '停摆诊室', sub: '安全节点', description: '让伤口追上病历' },
  shop2: { type: 'shop', id: 'shop2', icon: '铺', title: '昨日典当行', sub: '交易节点', description: '典当没有发生的东西' },
  rest5: { type: 'rest', id: 'rest5', icon: '息', title: '空白阅览室', sub: '安全节点', description: '在无人记录处休息' },
  rest6: { type: 'rest', id: 'rest6', icon: '息', title: '零号前厅', sub: '安全节点', description: '最后一次修改牌组' },
  shop3: { type: 'shop', id: 'shop3', icon: '铺', title: '未来遗失处', sub: '交易节点', description: '取回未来丢失的可能' },
}

export const ACT_NAMES = ['灰烬档案', '倒走之城', '第零号历史'] as const

export const CHAPTER_ENDINGS = [
  {
    eyebrow: 'ACT I CLOSED · ASHES REMEMBER',
    title: '火灾不是起点，而是一份删除指令',
    narrative: '封馆人的值班表上没有你的名字，却记录着你每一次醒来的时间。仓库大火并非为了毁掉证据，而是为了让整座城市忘记一名本该值夜的调查员。',
    reveal: '你从灰烬里找到一张车票：目的地写着“昨天”，发车时间是明天。',
    next: '进入第二幕 · 倒走之城',
  },
  {
    eyebrow: 'ACT II CLOSED · THE CLOCK CONFESSES',
    title: '循环不是牢笼，而是你寄回过去的工具',
    narrative: '失刻钟匠承认，倒走的城市只是更大装置的表盘。真正驱动循环的不是钟楼，而是档案馆地下那份从未建立、却被所有记录引用的“第零号历史”。',
    reveal: '订单上的签名确实属于三天后的你。你曾要求钟匠确保今晚永远能够重来。',
    next: '进入第三幕 · 第零号历史',
  },
] as const
